import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  main: [
    {
      type: 'autogenerated',
      dirName: 'claude-code',
    },
    {
      type: 'autogenerated',
      dirName: 'cursor',
    },
    {
      type: 'autogenerated',
      dirName: 'superpowers',
    },
    {
      type: 'autogenerated',
      dirName: 'investment',
    },
    {
      type: 'autogenerated',
      dirName: 'vibe-coding',
    },
  ],
};

export default sidebars;